// Catalog actions
export const CATALOG_NEEDS_SCROLL = 'CATALOG_NEEDS_SCROLL';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_SEARCH = 'SET_SEARCH';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const SET_OFFSET = 'SET_OFFSET';

// Catalog item actions
export const FETCH_CATALOG_ITEM_REQUEST = 'FETCH_CATALOG_ITEM_REQUEST';
export const FETCH_CATALOG_ITEM_FAILURE = 'FETCH_CATALOG_ITEM_FAILURE';
export const FETCH_CATALOG_ITEM_SUCCESS = 'FETCH_CATALOG_ITEM_SUCCESS';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const SELECT_SIZE = 'SELECT_SIZE';
export const RESET_CATALOG_ITEM = 'RESET_CATALOG_ITEM';

// Top sales actions
export const FETCH_TOP_SALES_REQUEST = 'FETCH_TOP_SALES_REQUEST';
export const FETCH_TOP_SALES_FAILURE = 'FETCH_TOP_SALES_FAILURE';
export const FETCH_TOP_SALES_SUCCESS = 'FETCH_TOP_SALES_SUCCESS';

// Nav bar actions
export const TOGGLE_NAV_BAR_SEARCH = 'TOGGLE_NAV_BAR_SEARCH';

// Cart actions
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
